### ISSUE TITLE
How use Firebase with Laravel Resource

### ISSUE THREAD

**Issue by trprado** [plokko/laravel-firebase#1]
If possible you have a example of how to use laravel-firebase with a resource. I actually created a test project using sql, but now I converted that project to use the firebase.

I use a resource in form:

```php
class Product extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id'            => $this->id,
            'name'          => $this->name,
            'price'         => (int)$this->price,
            'created_at'    => (string)$this->created_at,
            'updated_at'    => (string)$this->updated_at,
        ];
    }
}
```

Is possible to use resource with laravel-firebase?
Sorry by my ignorance, but I new in laravel and firebase.

**Comment by plokko** [comment]
@trprado i integrated a [full eloquent model sync](https://github.com/plokko/laravel-firebase/blob/master/docs/DB_sync.md) in this package and you can customize what and how it will be converted to firebase with the `toFirebase` method.
I recommend this approach and i have an app build on that synching a lot of tables with complex relations auto synched if a related model is updated, even m-n over m-n relations ! 👍 

If you want to use "raw" queries just set a reference with your array value, the data can be anything that can be converted to Json so a resource should be ok.
Example:
```php
$products= FirebaseDb::getReference('products');
$products->set('1',$product);
```
Firebase db is really simple to understand: it's a Json tree so you can overwrite any given path with an array (you can even overwrite the root element with a new json representation of the database if you want!)

sorry for the incomplete documentation but i'm still working on it.
A (maybe) more complete documentation should be found at the [php-firebase](https://github.com/plokko/firebase-php/blob/master/docs/DB.md).

**Comment by trprado** [comment]
Thank you for the answer.

I have another doubt, if I use `$products = FirebaseDb::getReference('products');`, the function return an array of objects containing all of my data, but the first value is 0: null and my item begins at the second. 

Another problem that I have is to know how to use firebase to generate uuid instead of the id generated in the Laravel. Firebase is getting this id value using as it identification and beginning in one of his value. I do not know if the problem is because all data is saved in a sqlite database or another error was created by me.

**Comment by plokko** [comment]
A reference is not an array and do not contain any data but a class that is used to reference a path:
they have no other  use than facilitating the linking and concatenation of paths and subpaths.
It may be buggy if you're using not as intended as you're doing it now (i planned to retreive the data anyway if used as a data source but for now it's not fully implemented), you should use the `get` function directly.

```php
//Create a reference to the /products path
$products = FirebaseDb::getReference('products');
//List ALL the products
var_dump($products->get(''));
//Get /product/1
var_dump($products->get('1'));
//Get a reference of /product/1 :  as you can see i can use 
// the previous created reference to facilitate the concatenation
$product1 = $products->getReference('1');
//Get /products/1 by reference
var_dump($product1->get(''));
//Get  /products/1/name
var_dump($product1->get('name'));
//You can also get a reference of any subpath for example /products/1/name
$product1name = $product1->getReference('name');
```
