### ISSUE TITLE
Requested entity was not found

### ISSUE THREAD

**Issue by AucT** [plokko/laravel-firebase#10]
DO you know what this error is about?

`Requested entity was not found. {"userId":1,"exception":"[object] (Plokko\\Firebase\\FCM\\Exceptions\\UnspecifiedErrorException(code: 404): Requested entity was not found. at /home/www/laravel/vendor/plokko/firebase-php/src/FCM/Exceptions/FcmErrorException.php:90)`

I'm suing in laravel notifications toFcm

```
public function toFcm($notifiable)
    {
        return FCM::notificationTitle("{$this->fromUser->name} Has Sent You Message")
            ->notificationBody("{$this->fromUser->name} Has Sent You Message")
            ->toDevice($notifiable->fcm_token);
    }
```

**Comment by plokko** [comment]
This is a Firebase error not a library error; it seems it can't find your device, maybe wrong fcm_token?
Try to debug it in Firebase
