### ISSUE TITLE
How to switch between multiple service accounts

### ISSUE THREAD

**Issue by binodav** [plokko/laravel-firebase#2]
I have multiple applications with different service accounts, how can I switch between them on the fly ? If it's not possible now, I would love to see it in the next version.

**Comment by plokko** [comment]
It's perfectly doable even if i've not yet implemented it:
laravel-firebase is just a Laravel wrapper of my firebase-php implementation so it's a matter of specifying a non-default ServiceAccount configuration.
That said there are a lot of implementing approach, i'll think about it.
