### ISSUE TITLE
SyncRelatedWithFirebase not working, and updating database does not sync with Firebase.

### ISSUE THREAD

**Issue by Xoshbin** [plokko/laravel-firebase#5]
Hi, I'm sorry that I'm opening issues frequently, But I'm really using this library as one of my main features on my application. anyway, the SyncRelatedWithFirebase is not working so the relationships doesn't affect the database on Firebase, And when I'm updating on of the columns from my database on Laravel it's not synced on Firebase database so the old data remains the same on firebase. and that's my code:

```
use Illuminate\Database\Eloquent\Model;
use \JordanMiguel\LaravelPopular\Traits\Visitable;
use Plokko\LaravelFirebase\Traits\SyncWithFirebase;
use Plokko\LaravelFirebase\Traits\SyncRelatedWithFirebase;

class Post extends Model
{
    use Visitable, SyncWithFirebase,
        SyncRelatedWithFirebase;
    protected $hidden = ['featured'];


    /**
     * Specifies the relations that needs to be automatically synched with firebase
     * @return array relations to be synched with firebase, default []
     */
    protected function getRelationsToSyncWithFirebase(){
        return [
          'source',
          'category'
        ];
    }

    /**
     * Get the user that owns the phone.
     */
    public function source()
    {
        return $this->belongsTo('App\Source', 'source_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function visit()
    {
        return $this->hasMany('App\Visit', 'category_id');
    }

    public function getViewsInPastDays(int $days)
    {
        return $this->getViews(Period::pastDays($days));
    }
}
```

**Comment by plokko** [comment]
Does Source and Category implement SyncWithFirebase?
ALL the models that need to be sync with Firebase must use it!
Keep also in mind that if you need to update Post when the related are updated you need to use SyncRelatedWithFirebase also in said classes.

By the way why you need to sync related model if you do not use them in this class serialization?
You need to use SyncRelatedWithFirebase  ONLY if you serialized something from those relations;
for example if Post contains an array of categories, in that case if a category is modified the category will be sync with Firebase but not the serialized Post data.
 Example:
```php
public function toFirebase(){
    return [
    'id'=>$this->id,
    'title'=>$this->title,
    'categories'=> $this->category->pluck('name'),//This need to be re-calculated if related categories are changed!
  ];

}
```

To trigger a Post re-sync on category change you need to define those relations like so:

```php
    protected function getRelationsToSyncWithFirebase(){
        return [
          'category'
        ];
    }
```

PS: keep in mind that firebase sync are triggered ONLY if the model data changes, in an m-n relation for example both tables are left untouched, this is one of the examples that needs SyncRelatedWithFirebase.

**Comment by Xoshbin** [comment]
@plokko  Thanks for the reply, I need the categories to list the posts by categories and grab categroies names, Anyway for the "update" part I did test it without "SyncRelatedWithFirebase " so only just posts was synced and still not working.

```
class Post extends Model
{
    use Visitable, SyncWithFirebase;
    protected $hidden = ['featured'];

    /**
     * Get the user that owns the phone.
     */
    public function source()
    {
        return $this->belongsTo('App\Source', 'source_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id');
    }
}

```

and my controller:
```
public function incrementView($id)
    {
        $post = Post::findOrFail($id);
        $post->increment('visited');
        $post->save();
    }
```

**Comment by plokko** [comment]
If you were synching the categories SyncRelatedWithFirebase usage is justified: it simply "wraps" all the relations so if you use them the related model are synched.
I did test it in a big database, with lot of relations and synching was working fine, please try to specify the fillable fields or just implement the toFirebase method.

**Comment by Xoshbin** [comment]
I followed all of what you gave, Now I'm getting all the categories names to a post which it's wrong because the post belongs only to one category it should return just on category that the post belongs to no returning all the categories. anyway this part is not important for me because I solved it on the client side but I think we still have to test it. The important part for me right now is the update part my database still not updated when it's updated on Laravel yet. I think you already know what's happening from my code above, I have posts that when visitor's click on the posts the "visited" column is incremented by 1, but it's not being synced with Firebase!!!

```
use Illuminate\Database\Eloquent\Model;
use \JordanMiguel\LaravelPopular\Traits\Visitable;
use Plokko\LaravelFirebase\Traits\SyncWithFirebase;
use Plokko\LaravelFirebase\Traits\SyncRelatedWithFirebase;

class Post extends Model
{
    use Visitable, SyncWithFirebase,
    SyncRelatedWithFirebase;
    protected $hidden = ['featured'];

    protected function getRelationsToSyncWithFirebase(){
        return [
          'source',
          'category'
        ];
    }


    public function toFirebase(){
        return [
        'id'=>$this->id,
        'title'=>$this->title,
        'categories'=> $this->category->pluck('name'),//This need to be re-calculated if related categories are changed!
        'sources'=> $this->category->pluck('name'),
        'excerpt'=>$this->excerpt,
        'slug'=>$this->slug,
        'image_url'=>$this->image_url,
        'status'=>$this->status,
        'created_at'=>$this->created_at,
        'title'=>$this->title,
      ];

    }

    /**
     * Get the user that owns the phone.
     */
    public function source()
    {
        return $this->belongsTo('App\Source', 'source_id');
    }

    /**
     * Get the user that owns the phone.
     */
    public function category()
    {
        return $this->belongsTo('App\Category', 'category_id');
    }

    public function getViewsInPastDays(int $days)
    {
        return $this->getViews(Period::pastDays($days));
    }
}

```

```
class Category extends Model
{
    use Translatable,
        HasRelationships,
        SyncWithFirebase,
        SyncRelatedWithFirebase;


    protected function getRelationsToSyncWithFirebase(){
        return [
          'post'
        ];
    }

    protected $translatable = ['slug', 'name'];

    protected $table = 'categories';

    protected $fillable = ['slug', 'name'];

    public function post()
    {
        return $this->hasMany('App\Post');
    }

    public function parentId()
    {
        return $this->belongsTo(self::class);
    }
}
```

and the source model is same as category model, and the controller is same as my last post, not changed.

**Comment by plokko** [comment]
Your code is correct, the toFirebase method will serialize everything you want, if the serialized categories are wrong it's your relation/code at fault.
If you mean ALL categories and posts are sync with firebase it's an expected feature:
the object of this package is to have a 1:1 updated copy of your database on Firebase.
If you need to add user restriction on the database please see Firebase rules on official documentation.

For the "visited" field you did not sync it with Firebase so it's normal it won't be sync; 
i did not try the increment function but it should trigger the save method so it should work as intended.
